"""BorrowedBook fix

Revision ID: 6b30148d4419
Revises: 603b4fc52b01
Create Date: 2025-05-23 11:53:23.671572

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "6b30148d4419"
down_revision: Union[str, None] = "603b4fc52b01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
