"""empty message

Revision ID: 73d1bbf8fd2f
Revises: 906684f00906
Create Date: 2025-05-22 06:43:41.584046

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "73d1bbf8fd2f"
down_revision: Union[str, None] = "906684f00906"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
