"""BorrowedBook fix

Revision ID: 603b4fc52b01
Revises: 9cf0d5279c7e
Create Date: 2025-05-23 07:41:13.538131

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "603b4fc52b01"
down_revision: Union[str, None] = "9cf0d5279c7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
