"""BorrowedBook fix

Revision ID: e56c2f492cd2
Revises: 6b30148d4419
Create Date: 2025-05-23 11:57:15.104336

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e56c2f492cd2"
down_revision: Union[str, None] = "6b30148d4419"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
